### ISSUE TITLE
Drop setup if it's empty

### ISSUE THREAD

**Issue by CyberAP** [vuejs/function-api-converter#4]
If I pass a component with a prop but without data I'll get an empty object in the setup return.

Input:

```javascript
export default {
  name: 'MyComponent',
  props: {
    item: Object,
  }
}
```

Output:

```javascript
export default {
  name: 'MyComponent',

  props: {
    item: Object
  },

  setup() {
    return {}
  }
}
```

Should be (probably):

```javascript
export default {
  name: 'MyComponent',

  props: {
    item: Object
  },

  setup(props) {
    return { ...props }
  }
}
```

**Comment by posva** [comment]
Shouldn't the `setup` function be dropped altogether?

**Comment by CyberAP** [comment]
Probably, it's still not clear to me why props are available on the render context without being explicitly passed in the setup function, since setup could overwrite them.

**Comment by posva** [comment]
Since props are already declared in `props`, it would be redundant to have to return them as well. You cannot/shouldn't change the value of a prop because they're read only, you can however override the value by variable shadowing

**Comment by Akryum** [comment]
Yeah `setup` should be dropped if it contains no statements other than an empty return.
